// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5N1U-wezGg6uLyil2Dgp50_O6M3BBeo',
    appId: '1:925308622228:web:359ab14e56e36929142b81',
    messagingSenderId: '925308622228',
    projectId: 'evently-app-b1ce1',
    authDomain: 'evently-app-b1ce1.firebaseapp.com',
    storageBucket: 'evently-app-b1ce1.firebasestorage.app',
    measurementId: 'G-1X7X53K0KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo7T-afxLrN0XRO6AhflY_4zZMTSChDkw',
    appId: '1:925308622228:android:92ff51003883fb5a142b81',
    messagingSenderId: '925308622228',
    projectId: 'evently-app-b1ce1',
    storageBucket: 'evently-app-b1ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiWRO-spYB4uYgw7i9EQ2NXH29d0XVuDc',
    appId: '1:925308622228:ios:470648aa38cb4b55142b81',
    messagingSenderId: '925308622228',
    projectId: 'evently-app-b1ce1',
    storageBucket: 'evently-app-b1ce1.firebasestorage.app',
    iosBundleId: 'com.example.eventlyapproute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiWRO-spYB4uYgw7i9EQ2NXH29d0XVuDc',
    appId: '1:925308622228:ios:470648aa38cb4b55142b81',
    messagingSenderId: '925308622228',
    projectId: 'evently-app-b1ce1',
    storageBucket: 'evently-app-b1ce1.firebasestorage.app',
    iosBundleId: 'com.example.eventlyapproute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW5N1U-wezGg6uLyil2Dgp50_O6M3BBeo',
    appId: '1:925308622228:web:125ba5dc4302f715142b81',
    messagingSenderId: '925308622228',
    projectId: 'evently-app-b1ce1',
    authDomain: 'evently-app-b1ce1.firebaseapp.com',
    storageBucket: 'evently-app-b1ce1.firebasestorage.app',
    measurementId: 'G-SYYVRW3JMW',
  );
}
